import type { FeedPayload } from "@/lib/radar/types";

const minutes = (m: number) => new Date(Date.now() + m * 60_000).toISOString();
const ago = (m: number) => new Date(Date.now() - m * 60_000).toISOString();

export const MOCK_FEED: FeedPayload = {
  scannedAt: ago(1),
  nextScanAt: minutes(1),
  signals: [
    {
      id: "rx-126234",
      status: "buy",
      kindLabel: "Сейчас",
      categories: ["now", "watches", "trend"],
      brand: "Rolex",
      model: "Datejust 36 Wimbledon",
      reference: "126234",
      sku: "RX-126234-WMB",
      imageHint: "Product shot 4:5 — циферблат крупно",
      retail: 8300,
      cost: 9140,
      expectedResale: 12150,
      store: "Bucherer · Zürich",
      stock: "1 в наличии",
      checkedAt: ago(4),
      launchAt: minutes(2),
      why: "Единственная позиция в регионе за 11 дней, спрос по запросам вырос на 42% за две недели.",
      factors: ["Последняя единица", "Запросы +42% / 14 дн", "Ликвидность 6 дней"],
    },
    {
      id: "ct-wssa0018",
      status: "buy",
      kindLabel: "Рестоки",
      categories: ["now", "restock", "watches"],
      brand: "Cartier",
      model: "Santos de Cartier Large",
      reference: "WSSA0018",
      sku: "CT-SA-0018-ST",
      imageHint: "Product shot 4:5 — лицевой кадр на нейтральном фоне",
      retail: 8250,
      cost: 8990,
      expectedResale: 12400,
      store: "Cartier Boutique · Dubai Mall",
      stock: "2 в наличии",
      checkedAt: ago(3),
      launchAt: minutes(9),
      why: "Модель ушла из наличия в 4 из 6 отслеживаемых бутиков за последние 9 дней, а вторичный рынок держит премию восемь недель подряд.",
      factors: ["Дефицит 4/6 бутиков", "Премия +38% · 8 недель", "Рестоки раз в 5 недель"],
    },
    {
      id: "lc-19091",
      status: "buy",
      kindLabel: "Clearance",
      categories: ["now", "clearance", "tech"],
      brand: "Leica",
      model: "Q3 43 Compact",
      reference: "19091",
      sku: "LC-19091-Q343",
      imageHint: "Product shot 4:5 — корпус камеры сбоку",
      retail: 6900,
      cost: 5980,
      expectedResale: 7850,
      store: "Leica Store · Wetzlar Outlet",
      stock: "3 в наличии",
      checkedAt: ago(12),
      launchAt: minutes(29),
      why: "Официальная уценка витринных единиц с полной гарантией, вторичный рынок не реагировал на снижение.",
      factors: ["Уценка −13%", "Гарантия 2 года", "Спред стабилен 5 нед"],
    },
    {
      id: "nk-fv5029",
      status: "prepare",
      kindLabel: "Скоро",
      categories: ["soon", "sneakers", "trend"],
      brand: "Nike",
      model: "Air Jordan 4 Retro Bred Reimagined",
      reference: "FV5029-006",
      sku: "NK-FV5029-006",
      imageHint: "Product shot 4:5 — пара под углом 3/4",
      retail: 215,
      cost: 268,
      expectedResale: 430,
      store: "SNKRS · EU Draw",
      stock: "Дроп в очереди",
      checkedAt: ago(1),
      launchAt: minutes(66),
      why: "Тираж ниже прошлого релиза, розыгрыш открывается через час — заявку нужно собрать заранее.",
      factors: ["Тираж −30%", "Draw через 1 ч", "Размерная сетка 42–44"],
    },
    {
      id: "ap-mu9e3",
      status: "prepare",
      kindLabel: "Рестоки",
      categories: ["restock", "tech"],
      brand: "Apple",
      model: "Mac Studio M4 Ultra 256 ГБ",
      reference: "MU9E3",
      sku: "AP-MU9E3-256",
      imageHint: "Product shot 4:5 — корпус сверху",
      retail: 9499,
      cost: 9820,
      expectedResale: 11300,
      store: "Apple Store · Frankfurt",
      stock: "Ожидается партия",
      checkedAt: ago(8),
      launchAt: minutes(87),
      why: "Конфигурация с максимальной памятью уходит в первые часы после поступления, наценка держится до нормализации сроков.",
      factors: ["Срок поставки 7 нед", "Наценка +18%", "Партия ожидается сегодня"],
    },
    {
      id: "pr-9922-gt3t",
      status: "client",
      kindLabel: "Тренды",
      categories: ["soon", "trend", "cars"],
      brand: "Porsche",
      model: "911 GT3 Touring 992.2",
      reference: "992-GT3-T",
      sku: "PR-9922-GT3T",
      imageHint: "Product shot 4:5 — профиль автомобиля",
      retail: 248000,
      cost: 271500,
      expectedResale: 339000,
      store: "Porsche Zentrum · München",
      stock: "Слот аллокации",
      checkedAt: ago(26),
      launchAt: minutes(140),
      why: "Аллокация под клиента: слот подтверждается только при внесённом депозите, окно закрывается в течение суток.",
      factors: ["Депозит 10%", "Окно 24 ч", "Лист ожидания 14 мес"],
    },
  ],
  newsItems: [],
  sources: [
    { name: "cartier.com/boutique-stock", state: "ok", detail: "42 с" },
    { name: "bucherer.com/ch", state: "ok", detail: "61 с" },
    { name: "nike.com/snkrs-eu", state: "throttled", detail: "4 мин" },
    { name: "leica-store.de", state: "ok", detail: "2 мин" },
    { name: "porsche-zentrum.de", state: "manual", detail: "26 мин" },
    { name: "apple.com/de/shop", state: "ok", detail: "38 с" },
  ],
  logs: [
    "12:04:11  scan cycle #8412 finished · 6 signals kept, 214 discarded",
    "12:04:09  price delta rolex/126234 · 9 140 → 9 140 (no change)",
    "12:03:58  stock drop cartier/WSSA0018 · 3 → 2 · boutique dubai-mall",
    "12:03:41  snkrs-eu rate limit · retry in 240 s",
    "12:02:30  new listing leica/19091 · outlet channel · confidence 0.86",
    "12:01:12  allocation slot porsche/992-GT3-T · deposit window opened",
    "11:58:44  margin recalc batch · 6 items · fx eur/chf 0.9412",
  ],
};
